<?php require_once 'header.php'?>

<section id="politicasprivacidad">
	<div class="container">
		<div class="row">
			<div class="politicasprivacidad-container">
				<div class="politicasprivacidad-text">
					<h4 class="title">Políticas de Privacidad</h4>

					<h5 class="subtitle">Condiciones de uso y política de privacidad para aplicaciones móviles y acceso desde dispositivos móviles.</h5>

					<h5 class="t1">1. Condiciones generales de uso</h5>
					<p class="p1">El presente documento tiene por objeto establecer las Condiciones Generales de Uso de las aplicaciones móviles titularidad de DROPSHIPPING S.A. (en adelante LA EMPRESA) con domicilio social en Chilavert 6780 constituida en fecha 8 de febrero de 2019 con domicilio en la Ciudad Autónoma de Buenos Aires e inscripta en la Inspección General de Justicia bajo el número 3214, del Libro 93 de Sociedades por acciones en fecha 14/02/2019.<br>
				    LA EMPRESA se reserva el derecho a modificar las presentes Condiciones de Uso con el objeto de adecuarlas a la legislación vigente aplicable en cada momento. Las presentes Condiciones de Uso no excluyen la posibilidad de que determinados Servicios de las aplicaciones, por sus características particulares, sean sometidos, además de a las Condiciones Generales de Uso, a sus propias condiciones particulares de uso (en adelante las Condiciones Particulares).<br>
				    La Empresa podrá, en cualquier momento y sin necesidad de previo aviso, realizar cambios y actualizaciones de las presentes Condiciones de Uso y de la Política de Privacidad. Estos cambios serán publicados en la Web y en la/s Aplicación/es y serán efectivos desde el momento de su publicación. Como consecuencia de lo anterior, el Usuario deberá revisar periódicamente si hay cambios en estas Condiciones y, tanto si existe consentimiento expreso como si no, si el Usuario continua usando el Servicio tras la publicación, ello implica la aceptación y asunción de los mismos. En caso de que no esté de acuerdo con las actualizaciones de las Condiciones de uso o de la Política de Privacidad, podrá renunciar dejando de usar el Servicio. El acceso y descarga de la aplicación es gratuito salvo en lo relativo al coste de la conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso contratado por los usuarios. Determinados servicios son exclusivos para nuestros clientes y su acceso se encuentra restringido. La descarga y uso de la aplicación atribuye la condición de usuario de la misma (en adelante, el ‘Usuario') e implica la lectura, entendimiento y aceptación de todos los términos y condiciones recogidas por la presente.</p>
			
		
					<h5 class="t1">2. Uso de la aplicación móvil y sus servicios</h5>
					<p class="p1">El Usuario reconoce y acepta que el uso de los contenidos y/o servicios ofrecidos por la presente aplicación móvil será bajo su exclusivo riesgo y/o responsabilidad. El Usuario se compromete a utilizar la presente aplicación móvil y todo su contenido y Servicios de conformidad con la ley, la moral, el orden público y las presentes Condiciones de Uso, y las Condiciones Particulares que, en su caso, le sean de aplicación. Asimismo, se compromete hacer un uso adecuado de los servicios y/o contenidos de la aplicación móvil y a no emplearlos par caso, a las Condiciones Particulares que le sean de aplicación. A título enunciativo, y en ningún caso limitativo o excluyente, el Usuario se compromete a: - No introducir o difundir contenidos o propaganda de carácter racista, xenófobo, pornográfico, de apología del terrorismo o que atenten contra los derechos humanos. - No introducir o difundir en la red programas de datos (virus y software nocivo) susceptibles de provocar daños en los sistemas informáticos del proveedor de acceso, sus proveedores o terceros usuarios de la red Internet. - No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que atente contra los derechos fundamentales y las libertades públicas reconocidos constitucionalmente y en los tratados internacionales. - No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que constituya publicidad ilícita o desleal. - No transmitir publicidad no solicitada o autorizada, material publicitario, "correo basura", "cartas en cadena", "estructuras piramidales", o cualquier otra forma de solicitación, excepto en aquellas áreas (tales como espacios comerciales) que hayan sido exclusivamente concebidas para ello. - No introducir o difundir cualquier información y contenidos falsos, ambiguos o inexactos de forma que induzca a error a los receptores de la información. - No suplantar a otros usuarios utilizando sus claves de registro a los distintos servicios y/o contenidos de los Portales. - No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación de los derechos de propiedad intelectual e industrial, patentes, marcas o copyright que correspondan a los titulares de los Portales o a terceros. - No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación del secreto de las comunicaciones y la legislación de datos de carácter personal.</p>
					
					<h5 class="t1">3. Propiedad intelectual e industrial</h5>
					<p class="p1">LA EMPRESA se reserva todos los derechos sobre las marcas, nombres comerciales o demás signos distintivos, las patentes, y la propiedad intelectual, con respecto al contenido y diseño de la aplicación. Todos los contenidos de la misma, incluyendo sin carácter limitativo, textos, gráficos, imágenes, su diseño y los derechos de propiedad intelectual que pudieran corresponder a dichos contenidos, así como las marcas, nombres comerciales o cualquier otro signo distintivo son propiedad de DROPSHIPPING S.A., quedando reservados todos los derechos sobre los mismos. Las marcas, nombres comerciales o signos distintivos son titularidad de DROPSHIPPING S.A., sin que pueda entenderse que la descarga, acceso y uso de la aplicación le atribuya ningún derecho sobre las citadas marcas, nombres comerciales y/o signos distintivos.</p>

					<h5 class="t1">4. Exclusión de garantías. Responsabilida</h5>
					<p class="p1">LA EMPRESA no garantiza en todo momento la disponibilidad de acceso y continuidad del funcionamiento de la presente aplicación móvil y de sus servicios, por lo que LA EMPRESA no será responsable, con los límites establecidos en el Ordenamiento Jurídico vigente, de los daños y perjuicios causados al Usuario como consecuencia de la indisponibilidad, fallos de acceso y falta de continuidad de la presente aplicación móvil y sus Servicios.<br>
					LA EMPRESA responderá única y exclusivamente de los Servicios que preste por sí misma y de los contenidos directamente originados por la empresa e identificados con su copyright. Dicha responsabilidad quedará excluida en los casos en que concurran causas de fuerza mayor o en los supuestos en que la configuración de los dispositivos del Usuario no sea la adecuada para permitir el correcto uso de los servicios de Internet prestados por LA EMPRESA. La descarga, acceso y uso de la aplicación en los dispositivos móviles o similares, no implica la obligación por parte de DROPSHIPPING S.A. de controlar la ausencia de virus, gusanos o cualquier otro elemento informático dañino. Corresponde al Usuario, en todo caso, la disponibilidad de herramientas adecuadas para la detección y desinfección de programas informáticos dañinos.</p>

					<h5 class="t1">5. Conducta de los usuarios</h5>
					<p class="p1">LA EMPRESA no garantiza que los Usuarios de la presente aplicación móvil utilicen los contenidos y/o servicios del mismo de conformidad con la ley, la moral, el orden público, ni las presentes Condiciones Generales y, en su caso, las condiciones Particulares que resulten de aplicación. Asimismo, no garantiza la veracidad y exactitud, exhaustividad y/o autenticidad de los datos proporcionados por los Usuarios. DROPSHIPPING S.A. no será responsable, indirecta ni subsidiariamente, de los daños y perjuicios de cualquier naturaleza derivados de la utilización de los Servicios y Contenidos de la aplicación por parte de los Usuarios o que puedan derivarse de la falta de veracidad, exactitud y/o autenticidad de los datos o informaciones proporcionadas por los Usuarios, o de la suplantación de la identidad de un tercero efectuada por un Usuario en cualquier clase de actuación a través de la presente aplicación móvil. Por lo tanto, el uso de esta aplicación no implica la obligación por parte de LA EMPRESA de comprobar la veracidad, exactitud, adecuación, idoneidad, exhaustividad y actualidad de la información suministrada a través de la misma. DROPSHIPPING S.A. no se responsabiliza de las decisiones tomadas a partir de la información suministrada a través de la aplicación ni de los daños y perjuicios producidos en el Usuario o terceros con motivo de actuaciones que tengan como único fundamento la información obtenida en la aplicación.</p>
					

					<h5 class="t1">6. Política privacidad</h5>
					<p class="p1">DROPSHIPPING S.A. desea poner en conocimiento de los usuarios y clientes de la/s aplicación/es, la política llevada a cabo respecto al tratamiento de todos los datos de carácter personal que por la utilización de las funciones de la/s aplicación/es se faciliten a la empresa. Todos los datos que se solicitan a los usuarios y clientes a través de la aplicación para dispositivos móviles serán necesarios para prestar el servicio objeto del servicio en virtud del cual se ha procedido a la descarga e instalación de la/s aplicación/es en los correspondientes dispositivos.</p>

					<h5 class="t1">7. Consentimiento</h5>
					<p class="p1">La utilización de la aplicación dará lugar al tratamiento de datos de carácter personal que LA EMPRESA, en su caso, llevará a cabo de acuerdo con las normas y procedimientos internos establecidos al efecto, que son conocidos por los clientes y usuarios y autorizados por éstos. LA EMPRESA podrá subcontratar con otras empresas o profesionales la ejecución material de todas o alguna de las prestaciones de servicios sin que en ningún caso tal comunicación constituya una cesión de datos, garantizando a los clientes y usuarios de la aplicación que los datos facilitados no se aplicarán ni utilizarán con un fin distinto al establecido.</p>

					<h5 class="t1">8. Garantía y protección de datos</h5>
					<p class="p1">En el tratamiento de los datos de carácter personal, LA EMPRESA se compromete a garantizar y proteger las libertades públicas y los derechos fundamentales de las personas físicas y, especialmente, su honor y su intimidad familiar y personal, obligándose en este sentido, a efectuar el correspondiente tratamiento de datos de acuerdo con la normativa vigente en cada momento y a guardar el más absoluto secreto en relación con la información entregada por los clientes y usuarios. Los datos de carácter personal objeto de tratamiento no se utilizarán para otras finalidades que no se encuentren aquí recogidas o, en su caso, por otro documento o contrato que vinculase a ambas partes con condiciones particulares. LA EMPRESA, salvo consentimiento expreso por parte de los usuarios y clientes, no realizará cesiones ni comunicaciones de datos que no estén previstos en la normativa vigente.</p>

					<h5 class="t1">9. Calidad de los datos</h5>
					<p class="p1">En el tratamiento de los datos de carácter personal, LA EMPRESA se compromete a garantizar y proteger las libertades públicas y los derechos fundamentales de las personas físicas y, especialmente, su honor y su intimidad familiar y personal, obligándose en este sentido, a efectuar el correspondiente tratamiento de datos de acuerdo con la normativa vigente en cada momento y a guardar el más absoluto secreto en relación con la información entregada por los clientes y usuarios. Los datos de carácter personal objeto de tratamiento no se utilizarán para otras finalidades que no se encuentren aquí recogidas o, en su caso, por otro documento o contrato que vinculase a ambas partes con condiciones particulares. LA EMPRESA, salvo consentimiento expreso por parte de los usuarios y clientes, no realizará cesiones ni comunicaciones de datos que no estén previstos en la normativa vigente.</p>

					<h5 class="t1">10. Ejercicio de los derechos de acceso, rectificación, cancelación y oposición</h5>
					<p class="p1">LA EMPRESA informa de que los usuarios podrán ejercitar los derechos de acceso, rectificación, cancelación y oposición mediante el envío de un correo electrónico a WWW.ENTREGARWEB.COM.</p>

					<h5 class="t1">11. Medidas de seguridad</h5>
					<p class="p1">LA EMPRESA informa a los usuarios y clientes que, de conformidad con lo dispuesto por la normativa vigente, ha adoptado las medidas de índole técnica y organizativas necesarias para garantizar la seguridad de los datos de carácter personal y evitar la alteración, pérdida, tratamiento o acceso no autorizado, habida cuenta del estado de la tecnología, la naturaleza de los datos almacenados y los riesgos a que están expuestos. Igualmente LA EMPRESA garantiza al usuario el cumplimiento del deber de secreto profesional respecto de los datos personales de los usuarios y del deber de guardarlos.</p>

					<h5 class="t1">12. Modificación de la política de privacidad</h5>
					<p class="p1">LA EMPRESA se reserva el derecho a modificar su Política de Privacidad, de acuerdo a su propio criterio, o motivado por un cambio de los Organismos de contralor.</p>

					<h5 class="t1">13. Varios. Modificaciones</h5>
					<p class="p1">LA EMPRESA se reserva el derecho a efectuar las modificaciones que estime oportunas, pudiendo modificar, suprimir e incluir nuevos contenidos y/o servicios, así como la forma en que éstos aparezcan presentados y localizados.</p>

					<h5 class="t1">14. Menores de edad</h5>
					<p class="p1">Con carácter general, para hacer uso de los Servicios de la presente aplicación móvil los menores de edad deben haber obtenido previamente la autorización de sus padres, tutores o representantes legales, quienes serán responsables de todos los actos realizados a través de la presente aplicación móvil por los menores a su cargo. En aquellos Servicios en los que expresamente se señale, el acceso quedará restringido única y exclusivamente a mayores de 18 años.</p>

					<h5 class="t1">15. Duración y terminación</h5>
					<p class="p1">La prestación de los servicios y/o contenidos de la presente aplicación móvil tiene una duración indefinida. Sin perjuicio de lo anterior, LA EMPRESA está facultada para dar por terminada, suspender o interrumpir unilateralmente, en cualquier momento y sin necesidad de preaviso, la prestación del servicio y de la presente aplicación móvil y/o de cualquiera de los servicios, sin perjuicio de lo que se hubiera dispuesto al respecto en las correspondientes condiciones particulares.</p>

					<h5 class="t1">16. Ley y juridicción</h5>
					<p class="p1">Las cuestiones relativas a las Condiciones de Uso y Política de Privacidad, así como todas aquellas cuestiones que radican y tengan relación en parte o en su totalidad con los servicios suministrados a través de la aplicación, se rigen en todos y cada uno de sus extremos por la ley argentina, renunciando expresamente las partes al fuero que les corresponda, y sometiéndose a los Juzgados y Tribunales de la Capital Federal.</p>
				
				</div>
			</div>
		</div>
	</div>
</section>

<?php require_once 'footer.php'?>