<?php require_once 'header.php'?>

<section id="terminoscondiciones">
	<div class="container">
		<div class="row">
			<div class="terminoscondiciones-container">
				<div class="terminoscondiciones-text">
					<h4 class="title">Términos y condiciones</h4>

                    <h5 class="t1">Términos y condiciones de privacidad y uso de datos de app.entregar, www.entregarweb.com</h5>
					<p class="p1"><b>Términos y condiciones </b> Este contrato describe los términos y condiciones (los "Términos y Condiciones") aplicables al servicio ofrecidos por DROPSHIPPING S.A., CUIT N° 33716349069 con domicilio legal en CHILAVERT 6780 ,Ciudad Autónoma de Buenos Aires, dentro del sitio <span>https: WWW.ENTREGARWEB.COM o app</span> ENTERGAR , parte de nuestros clientes (en adelante denominados ,indistintamente los “Clientes” o “Usuarios”).</p>
					<p class="p1">Cualquier persona que desee acceder y/o usar el sitio o los servicios podrá hacerlo sujetándose a los Términos y Condiciones, junto con todas las demás políticas y principios que rigen la tienda virtual de DROPSHIPPING S.A., detallados a continuación.</p>
					<p class="p1">En consecuencia, todas las visitas y cada una de las operaciones y transacciones que se realicen en este sitio, como asimismo sus efectos jurídicos, quedarán regidos por estas reglas y sometidas a la legislación aplicable en la República Argentina.</p>
					<p class="p1">En consecuencia, todas las visitas y cada una de las operaciones y transacciones que se realicen en este sitio, como asimismo sus efectos jurídicos, quedarán regidos por estas reglas y sometidas a la legislación aplicable en la República Argentina.</p>
					<p class="p1">CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES, LOS CUALES TIENEN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</p>
					<p class="p1">En forma previa al uso del sitio y/o los servicios, el Usuario deberá leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones. Utilizar el sitio, implica haber aceptado las condiciones establecidas en los Términos y Condiciones y las políticas de la tienda virtual de LA EMPRESA.</p>
					<p class="p1">Por ello, se obliga a cumplir expresamente con las mismas.</p>

					<h5 class="t2">Capacidad</h5>
					<p class="p2">Los servicios y/o el sitio, sólo están disponibles para personas que tengan capacidad legal para contratar de acuerdo a la legislación vigente en la República Argentina. No podrán utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios que hayan sido suspendidos temporalmente o inhabilitados definitivamente.</p>
					<p class="p2">1. Es obligatorio completar el formulario de registración en todos sus campos con datos válidos para la adquisición de productos y servicios ofrecidos en este sitio. El futuro Usuario deberá completarlo con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario.</p>
					<p class="p2">2. LA EMPRESA, no se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados. Se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, se dará de baja la compra efectuada, sin que ello genere algún derecho a resarcimiento.</p>
					<p class="p2">3. La totalidad de los datos y claves aportados por los clientes y usuarios a todos los efectos requeridos por APP.ENTREGAR O WWW.ENTREGARWEB.COM, (en adelante LA EMPRESA), que acceden a los servicios prestados por ENTREGAR a través de su plataforma, aplicaciones moviles para webs, tablets y teléfonos o de su sitio web <span>WWW.ENTREGARWEB.COM</span> gozan del resguardo de ENTREGAR, quien se compromete a abstenerse de suministrar los mismos a terceros, salvo previa autorización del usuario, con excepción de requerimiento judicial o administrativo competente.</p>
					<p class="p2">4. El Usuario dispondrá, una vez registrado, de un nombre y contraseña o clave definitiva que le permitirá el acceso personalizado, confidencial y seguro. El Usuario tendrá la posibilidad de cambiar la clave de acceso, para lo cual deberá sujetarse al procedimiento establecido en el sitio respectivo. El Usuario se obliga a mantener la confidencialidad de su Clave de acceso, asumiendo totalmente la responsabilidad por el mantenimiento de la confidencialidad de su clave secreta registrada en este sitio web, la cual le permite efectuar compras, y obtener información. Dicha clave es de uso personal y su entrega a terceros, no genera responsabilidad de LA EMPRESA en caso de mala utilización.</p>
					<p class="p2">5. El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, por sí y/o por terceros, pues el acceso a la misma está restringido al ingreso y uso de su Clave Secreta, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Clave bajo cualquier título.</p>
					<p class="p2">LA EMPRESA, se reserva el derecho de rechazar cualquier solicitud de registración o de cancelar una registración previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p>
					<p class="p2">6. LA EMPRESA se reserva el derecho de modificar sin previo aviso las presentes condiciones, notificando de dichas modificaciones a sus usuarios oportunamente. El Usuario estará sujeto a los Términos y Condiciones vigentes al momento que realice el uso del sitio, salvo que por ley o decisión de organismos gubernamentales se deba hacer cambios con carácter retroactivo en dichos Términos y Condiciones, en cuyo caso, los posibles cambios afectarán también a los pedidos que hubiera hecho previamente el Usuario. En dicho caso se pondrá un aviso en el sitio alertando a los Usuarios sobre estos cambios, durante un tiempo razonable. Sin perjuicio de lo anterior, los Usuarios son responsables de leer estos términos y condiciones cada vez que ingresen al sitio y en forma previa a realizar cualquier transacción para ver si han sufrido modificaciones.</p>
					<p class="p2">7. La presente política de privacidad y protección de datos se presume aceptada por todo usuario y titular de datos, en un todo conforme las previsiones de la Ley 25326 y sus modificatorias.</p>
					<p class="p2">8. Los datos aportados por los usuarios serán utilizados por APP.ENTREGAR Y <span>WWW.ENTREGARWEB.COM</span> por cada operación y serán conservados por el término legal, vencido el cual el cliente presta entera conformidad para su definitiva eliminación.</p>
					<p class="p2">9. Al requerirse como medida de seguridad el empleo de claves y contraseñas de acceso para el uso de la plataforma, el usuario asume plena responsabilidad por el uso y seguridad de las mismas respecto de terceros, ya sea que los mismos accedan con el consentimiento del usuario, o sin él, deslindando toda responsabilidad de LA EMPRESA respecto de los eventuales daños y perjuicios que pudieren derivarse del uso indebido de la plataforma, tanto respecto del cliente usuario, su personal y/o de terceros, teniendo o careciendo de autorización del primero.</p>
					<p class="p2">10. LA EMPRESA no abonará al cliente usuario por concepto alguno ningún importe que eventualmente se le requiera contra la entrega de los envios gestionados a través de su página web, procediéndose en tal caso a la devolución del envío al remitente, sin cargo alguno para LA EMPRESA.</p>
					<p class="p2">11. El cliente deberá dar cumplimiento con el requisito de suscripción de la correspondiente Orden de Retiro a terceros o dependientes expresamente autorizados. En caso de incumplimiento con dicho requisito, LA EMPRESA procederá a la interrupción del envío hasta tanto se dé acabado cumplimiento con el mismo, sin responsabilidad alguna de LA EMPRESA.</p>
					<p class="p2">12. En el momento de la entrega del envío el autorizado deberá exhibir y firmar con aclaración y número de documento la respectiva autorización del cliente, caso contrario LA EMPRESA no procederá a la entrega y regresará el envio al depósito por donde el cliente deberá retirarlo luego de haber recibido de LA EMPRESA la correspondiente comunicación.</p>
					<p class="p2">13. LA EMPRESA queda liberada por el cliente de cualquier demora o inconveniente en la entrega del envío que obedezca a razones ajenas a su accionar y que no le resulten imputables, entre las que a mero título enunciativo se mencionan los paros o huelgas, marchas, cortes de calles, avenidas, accesos, puentes, caminos, rutas de aeronavegación, condiciones de aeronavegación, inconvenientes climáticos, y cualquier otra circunstancia de caso fortuito o fuerza mayor.</p>
					<p class="p2">14. El cómputo del plazo de entrega correrá a partir de la acreditación del pago mediante los medios habilitados por LA EMPRESA.</p>
					<p class="p2">15. En caso de encontrarse ausente el receptor del envío, ya sea el cliente o su autorizado,LA EMPRESA procederá a reenviarlo por segunda y única vez, y en caso de reiterarse la ausencia el cliente deberá retirar el envío del depósito, para lo cual contará con un plazo de quince dias (15) corridos, vencidos los cuales LA EMPRESA no se responsabiliza por los daños o deterioros o pérdidas que pudiere sufrir el envío.</p>
					<p class="p2">16. Para la aceptación del envío el tamaño de paquetes o cajas no podrá exceder de , 0pcion A) 1m3 ni de 30 kilos B)2m3 ni de 60- Kilos . En caso de incumplimiento de parte del cliente de dicha limitación, LA EMPRESA interrumpirá la entrega del envío comunicando al usuario de tal circunstancia por los medios que considere corresponder.</p>
					<p class="p2">17. Prohibiciones: El usuario asume haber sido notificado que se encuentra totalmente prohibido el envío de objetos peligrosos, inflamables, corrosivos, explosivos, perecederos, líquidos, joyas, dinero en efectivo, valores, tarjetas de débito o crédito, cheques, billetes de juegos de azar, material radiactivo, magnético, estupefacientes, animales y/o cualquier otro objeto que resulte actual o potencialmente peligroso, infeccioso. Se encuentra igualmente prohibido todo material cuyo uso o tenencia se encuentre prohibido por las leyes, o adquirido sin cumplimiento de los parámetros legales vigentes, y publicaciones en cualquier formato cuya divulgación se encuentre prohibida en todo el territorio nacional.</p>
					<p class="p2">18. La información contenida en los Términos y Condiciones y los contenidos del sitio no constituyen una oferta de venta, sino una invitación para contratar. No existirá ningún contrato entre LA EMPRESA y el Usuario en relación a ningún producto hasta que el pedido haya sido expresamente aceptado por LA EMPRESA. Si la transacción del Usuario no es aceptada y ya se le hubiese hecho algún cargo en su cuenta, el importe del mismo le será reintegrado en su totalidad. LA EMPRESA informará, de manera inequívoca y fácilmente accesible, los pasos que deben seguirse para concretar la operación. Se indicará, además, la dirección de correo postal o electrónico y los medios técnicos a disposición del consumidor para identificar y corregir errores en el envío o en sus datos.</p>
					<p class="p2">19. Los productos ofrecidos en este sitio, salvo que se señale una forma diferente para casos particulares u ofertas de determinados bienes o servicios, pueden ser pagados a través de tarjeta de crédito, tarjeta de débito, Mercado pago ,en efectivo (a través de los medios autorizados por la página) y transferencia por Red Link. Sin perjuicio de lo antes mencionado, los medios de pago podrán variar en cualquier momento. Dicho cambio será publicado en el sitio. Tratándose de tarjetas bancarias aceptadas en este sitio, los aspectos relativos a éstas, tales como la fecha de emisión; caducidad, cupo, bloqueos, etc., se regirán por el respectivo Contrato que celebró con el Banco o Tarjeta de Crédito, de tal forma que LA EMPRESA no tendrá responsabilidad en cualquiera de los aspectos señalados.</p>
					<p class="p2">20. PROPIEDAD INTELECTUAL La información, datos, textos gráficos, imágenes, fotografías, audio y video clips, logotipos, iconos, programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su cuenta, son de propiedad de LA EMPRESA y están protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. El uso indebido y la reproducción total o parcial de dichos contenidos quedan prohibidos, salvo autorización expresa y por escrito de LA EMPRESA.</p>
					<p class="p2">21. Uso de los datos personales registrados en el sitiowww.entreweb.com/app: Entregar ,El Usuario o Cliente Tiene derecho a retirar su consentimiento respecto del uso de los datos personales, así como a acceder a los mismos y a rectificarlos o cancelarlos si los datos que almacenamos son incorrectos o ilícitos por cualquier motivo. Aquellas personas físicas que hayan facilitado sus datos, podrán dirigirse a esta entidad, en su calidad de titular de los datos, con el fin de poder ejercitar gratuitamente sus derechos de acceso, rectificación, cancelación y oposición respecto de sus datos, conforme a la normativa vigente. Para modificar sus suscripciones, el usuario debe ponerse en contacto con nosotros para ejercer sus derechos de acceso, rectificación o cancelación, u oponerse al tratamiento de sus datos personales mediante comunicación por escrito dirigida a www.entregarweb.com a la dirección indicada al inicio o a la dirección de correo electrónico info@entregarweb.com.ar Conforme se establece en el artículo 14, inciso 3 de la Ley Nº 25.326, el titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo quem se acredite un interés legítimo al efecto. Se informa que la Dirección Nacional de Protección de Datos Personales, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales. Para el ejercicio de estos derechos simplemente se debe enviar una solicitud de consulta, rectificación, actualización y/o supresión, según el caso, mediante requerimiento escrito al domicilio del Organizador sito en calle Chilavert 6780 , Ciudad Autónoma de Buenos Aires o e-mail <span>info@entregarweb.com</span> y los datos serán informados, rectificados, actualizados y/o suprimidos dentro de los 5 (cinco) días hábiles de recibido el pedido.</p>
					<p class="p2">22. Sanciones. Suspensión de operaciones: Sin perjuicio de otras medidas, LA EMPRESA advertirá, suspenderá temporalmente o inhabilitará definitivamente la cuenta de un Usuario o una publicación e iniciará las acciones que estime pertinentes, y no le prestará sus servicios si:</p>
					<p class="p2">• Se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones y demás políticas de LA EMPRESA.<br>
					• Si incumpliera sus compromisos como Usuario.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<?php require_once 'footer.php'?>